language: node_js
sudo: required
dist: xenial
node_js: stable
branches:
  only:
  - hexo
before_install:
- openssl aes-256-cbc -K $encrypted_a9d6e61ffef9_key -iv $encrypted_a9d6e61ffef9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 119.3.248.174\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- export TZ='Asia/Shanghai'
- npm install hexo-cli
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- rsync -rv --delete -e 'ssh -o stricthostkeychecking=no -p 1022' public/ root@www.astrobear.top:/usr/astroblog
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  name: "$GIT_NAME"
  email: "$GIT_EMAIL"
  github_token: "$GITHUB_TOKEN"
  keep-history: true
  target-branch: master
  on:
    branch: hexo
